- name: nginx installation
  become: true
  hosts: backend
  tasks:
    - name: install nginx
      dnf:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
