- name: install packages
  hosts: backend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - gcc
    - git
    - mysql