- name: filters in ansible
  hosts: local
  connection: local
  tasks:
    - name: using default
      ansible.builtin.debug:
        msg: "{{ COURSE | default('Ramesh') }}"

    - name: dict to list
      vars:
        COURSE:
          COURSE_NAME: "devops"
          DURATION: "120HRS"
          TRAINER: "Siva"
      ansible.builtin.debug:
        msg: "{{ COURSE | dict2items }}"

    - name: list to dict
      vars:
        COURSE:
          - { "key": "name", "value": "devops" }
          - { "key": "duration", "value": "120HRS" }
          - { "key": "trainer", "value": "shiva" }
      ansible.builtin.debug:
        msg: "{{ COURSE | items2dict }}"

    - name: string to list
      vars:
        fruits: "apple,banana,orange"
      ansible.builtin.debug:
        msg: "{{ fruits | split(',') }}"
