- name: shell and command modules
  hosts: local
  connection: local
  tasks:
    - name: shell module
      ansible.builtin.shell: ls -ltr > /tmp/ouput.txt

    - name: command module
      ansible.builtin.command: ls -ltr
      register: command_result

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ command_result }}"
